name: Deploy to AWS ECR

on:
  push:
    branches:
      - main  # Triggers on push to main branch

jobs:
  deploy:
    name: Build & Push to ECR
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ap-south-1
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME=ritual-roast
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker Image to ECR
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME=ritual-roast
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest

      - name: Print Image URL
        run: echo "Image pushed to ${{ steps.login-ecr.outputs.registry }}/ritual-roast:latest"

