name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Triggers on push to main branch

jobs:
  deploy:
    name: Deploy to ECS Fargate
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ap-south-1
      AWS_REGION: ap-south-1
      ECR_IMAGE: ${{ secrets.ECR_REGISTRY }}/ritual-roast:latest
      ECS_CLUSTER: ritual-roast-cluster  
      ECS_SERVICE: ritual-roast-service  
      ECS_TASK_DEFINITION: ritual-roast-taskdefination  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download Current Task Definition
        run: |
          aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION --region $AWS_REGION \
            --query taskDefinition > task-definition.json

      - name: Update Task Definition with New Image
        run: |
          jq --arg IMAGE "$ECR_IMAGE" '.containerDefinitions[0].image = $IMAGE' task-definition.json > updated-task-definition.json

      - name: Register New Task Definition
        id: register-task
        run: |
          echo "TASK_DEFINITION_ARN=arn:aws:ecs:ap-south-1:836612222168:task-definition/ritual-roast-taskdefination:1" >> $GITHUB_ENV

      - name: Debug ARN Variable
        run: echo "Task Definition ARN: $TASK_DEFINITION_ARN"

      - name: Deploy Updated Task to ECS Service
        run: |
          if [ -z "$TASK_DEFINITION_ARN" ]; then
            echo "Error: TASK_DEFINITION_ARN is empty. Task definition registration may have failed."
            exit 1
          fi
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE \
            --task-definition $TASK_DEFINITION_ARN --force-new-deployment

